name: Trigger Deploy Repo
on:
  push:
    branches:
      - master

jobs:
  trigger-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger deploy workflow
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          repository: LucaDelmarche/DeployLulitaire
          event-type: deploy-trigger
